version: '3'
services:
  front1:
    build: ./front
    ports:
      - "81:80"
  front2:
    build: ./front
    ports:
      - "82:80"
  front3:
    build: ./front
    ports:
      - "83:80"
  nginx_front:
    build: ./nginx_front
    ports:
      - "80:80"
    depends_on:
     - front1
     - front2
     - front3


  back1:
    build: ./back
    ports:
      - "85:80"
  back2:
    build: ./back
    ports:
      - "86:80"
  back3:
    build: ./back
    ports:
      - "87:80"
  nginx_back:
    build: ./nginx_back
    ports:
      - "84:80"
    depends_on:
     - back1
     - back2
     - back3


  mongo1:
    hostname: mongo1
    container_name: mongo1
    image: mongo:4.1
    ports:
      - "40001:27017"
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
  mongo2:
    hostname: mongo2
    container_name: mongo2
    image: mongo:4.1
    ports:
      - "40002:27017"
    restart: always
    entrypoint: [ "/usr/bin/mongod","--bind_ip_all", "--replSet", "rs0" ]
  mongo3:
    hostname: mongo3
    container_name: mongo3
    image: mongo:4.1
    ports:
      - "40003:27017"
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
  mongo-config:
    hostname: mongo-config
    container_name: mongo-config
    image: mongo:4.1
    volumes:
      - ./scripts:/scripts
    entrypoint: [ "bash", "/scripts/rs-init.sh" ]
